
int main() {

  int a;

  try
  {
    a = 1;
  } catch (Exception ex)
  {
    a = 2;
    int b;
    int a;
  }


  return 0;
}

