
int main() {

  int a;
  Exception ex;
  int b;
  int c;
  
  try
  {
    a = 1;
  } catch (Exception ex)
  {
    a = 2;
  }
  
  a = 1;
  
  return 0;
}

